name: Build and Push Docker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_REGISTRY:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ${{ secrets.DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Get repository name
        id: get-repo-name
        uses: mariachibear/get-repo-name-action@v1.1.0
        with:
          string-case: "lowercase"

      - name: Build and Push
        env:
          DOCKER_IMAGE_PATH: ${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}
          RELEASE_VERSION: ${{ inputs.tag }}
          REPOSITORY_NAME: ${{ steps.get-repo-name.outputs.repository-name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_PATH }}/${{ env.REPOSITORY_NAME }}:latest
            ${{ env.DOCKER_IMAGE_PATH }}/${{ env.REPOSITORY_NAME }}:${{ env.RELEASE_VERSION }}
