name: Continuous Deployment

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      HOST_CMDS:
        required: true
      PRODUCTION_ENV:
        required: true
      SSH_HOST:
        required: true
      SSH_KEY:
        required: true
      SSH_PASSPHRASE:
        required: true
      SSH_USER:
        required: true

jobs:
  docker:
    needs: setup
    uses: mariachibear/cutting-ninja-api/.github/workflows/docker_build_push.yml@master
    with:
      tag: ${{ needs.setup.outputs.tag }}
    secrets: inherit

  ssh:
    needs: [setup, docker]
    uses: mariachibear/cutting-ninja-api/.github/workflows/ssh_deploy.yml@master
    secrets: inherit
