name: Docker Image Deploy

on:
  create:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set up Docker Image version tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - 
        name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja:latest
      #       ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja:${{ env.RELEASE_VERSION }}
