name: Docker Image Build && Push

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Get tag version
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
        with:
          context: .
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja-api:${{ env.RELEASE_VERSION }}

