name: Docker Build & Push

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ inputs.tag }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/cutting-ninja-api:${{ env.RELEASE_VERSION }}
