name: Production Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag version
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

  ci:
    needs: setup
    uses: mariachibear/cutting-ninja-api/.github/workflows/continuous_integration.yml@master
    secrets: inherit

  cd:
    needs: [setup, ci]
    uses: mariachibear/cutting-ninja-api/.github/workflows/continuous_deployment.yml@master
    with:
      tag: ${{ needs.setup.outputs.tag }}
    secrets: inherit

  rebase_develop:
    needs: [setup, ci, cd]
    uses: mariachibear/cutting-ninja-api/.github/workflows/rebase_to_master.yml@master
    with:
      tag: develop
