name: Production Deployment

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  setup :
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Get tag version
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

  docker:
    needs: setup

    uses: mariachibear/cutting-ninja-api/.github/workflows/docker_build_push.yml@master
    with:
      tag: ${{ needs.setup.outputs.tag }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  deploy:
    needs: [setup, docker]

    runs-on: ubuntu-latest
    
    steps:      
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Create ENV file
        run: echo $PRODUCTION_ENV >> ./.env.production
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
      - 
        name: Push ENV file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./.env.production"
          target: "~/github"
      - 
        name: Deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ${{ secrets.HOST_CMDS }}
    
