name: Production Deployment

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag version
        id: get-tag
        uses: wyrihaximus/github-action-get-previous-tag@v1
        with:
          fallback: ${{ inputs.tag }}

  continuous_integration:
    needs: [setup]
    secrets: inherit
    uses: ./.github/workflows/continuous_integration.yml

  docker:
    needs: [setup, continuous_integration]
    secrets: inherit
    uses: ./.github/workflows/build_and_push_docker.yml
    with:
      tag: ${{ needs.setup.outputs.tag }}

  ssh:
    needs: [setup, continuous_integration, docker]
    secrets: inherit
    uses: ./.github/workflows/ssh_deploy.yml

  develop-branch:
    needs: [setup, continuous_integration, docker, ssh]
    uses: ./.github/workflows/rebase_to_master.yml
    with:
      branch_name: "develop"
