name: Production Deployment

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      repository-name: ${{ steps.repo-name.outputs.repository-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag version
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "no-tag"

      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          string-case: "lowercase"
          with-owner: "true"

  continuous_integration:
    needs: [setup]

    uses: ./.github/workflows/continuous_integration.yml@${{github.event.repository.default_branch}}

    secrets: inherit

  docker:
    needs: [setup, continuous_integration]

    if: needs.setup.outputs.tag != 'no-tag'

    uses: ./.github/workflows/build_and_push_docker.yml@${{github.event.repository.default_branch}}
    with:
      tag: ${{ needs.setup.outputs.tag }}
    secrets: inherit

  ssh:
    needs: [setup, continuous_integration, docker]

    if: needs.setup.outputs.tag != 'no-tag'

    uses: ./.github/workflows/ssh_deploy.yml@${{github.event.repository.default_branch}}

    secrets: inherit

  develop_branch:
    needs: [setup, continuous_integration, docker, ssh]

    if: needs.setup.outputs.tag != 'no-tag'

    uses: ./.github/workflows/rebase_to_master.yml@${{github.event.repository.default_branch}}

    with:
      branch_name: "develop"
