name: SSH Deploy

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      SSH_PASSPHRASE:
        required: true
      HOST_CMDS:
        required: true
      PRODUCTION_ENV:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create ENV file
        run: echo "$PRODUCTION_ENV" >> ./.env.production
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}

      - name: Push ENV file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./.env.production"
          target: "~/github"
          username: ${{ secrets.SSH_USER }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: ${{ secrets.HOST_CMDS }}
          username: ${{ secrets.SSH_USER }}
